eureka:
  client:
    fetchRegistry: false #\u81EA\u5DF1\u63D0\u4F9B\u670D\u52A1\uFF0C\u6240\u6709\u8BBE\u7F6E\u4E3Afalse
    registerWithEureka: false #\u4E0D\u9700\u8981\u53BB\u68C0\u7D22\u670D\u52A1\uFF0C\u6240\u6709\u8BBE\u7F6E\u4E3Afalse
server:
  port: 9000
spring:
  application:
    name: springcloud-eureka
